version: '3'
services:
  db:
    container_name: CogartStudio
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cogart_studio
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/cogartStudio-data:/var/lib/postgresql/data
